### ISSUE TITLE
How do you compile the type script?

### ISSUE THREAD

**Issue by hurricaneLTG** [marvinkassabian/ray-casting-engine#2]
also I get a black screen and no errors in the console.

**Comment by marvinkassabian** [comment]
Hey, my TypeScript code gets compiled through the TypeScript addon for
Atom, but you can also use Grunt, and that will do it. I believe the
necessary packages are in the project.json file.

Since there is no compiled JavaScript on my repo, nothing is drawing to the
canvas, that's why it's black.

**Comment by hurricaneLTG** [comment]
ahha thats sweet. I can see boxes and jump in a geriatric fashion
